name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt-openjdk'
          java-version: '11'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Set up CodeQL
        uses: github/codeql-action/setup@v3
        with:
          languages: java

      - name: Analyze code with CodeQL
        uses: github/codeql-action/analyze@v3
